# Generated by Django 4.1 on 2022-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_vendor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ManyToManyField(blank=True, null=True, to='Services.package'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='Services.service'),
        ),
    ]
